### ISSUE TITLE
found this error in bug bag 

### ISSUE THREAD

**Issue by im2fuzzy** [smaitch/Grail#151] opened 2020-03-16 17:19 UTC
bug bag gave me this info as an issue to my addon as follows 

1x Grail\Grail-108.lua:9763: script ran too long
[string "@Grail\Grail-108.lua"]:9763: in function `_RawNPCLocations'
[string "@Grail\Grail-108.lua"]:8242: in function `NPCLocations'
[string "@Grail\Grail-108.lua"]:9374: in function <Grail\Grail.lua:9362>
[string "=(tail call)"]: ?
[string "@Grail\Grail-108.lua"]:5883: in function `?'
[string "@Grail\Grail-108.lua"]:1386: in function `?'
[string "@Grail\Grail-108.lua"]:10580: in function `_Tooltip_OnEvent'
[string "@Grail\Grail-108.lua"]:11166: in function <Grail\Grail.lua:11166>

Locals:
self = <table> {
 QuestBreadcrumbsFor = <function> defined @Grail\Grail.lua:9196
 bitMaskClassPriest = 256
 IsBugged = <function> defined @Grail\Grail.lua:7067
 bitMaskGenderMale = 8192
 _RecordArtifactLevels = <function> defined @Grail\Grail.lua:9794
 bitMaskCompleted = 1
 _PrepareWorldQuestSelfNewNPCs = <function> defined @Grail\Grail.lua:3390
 QuestLocationsAccept = <function> defined @Grail\Grail.lua:9354
 QuestLocationsAccept = <function> defined @Grail\Grail.lua:9354
 IsAvailable = <function> defined @Grail\Grail.lua:7049
 NO_SKILL = -1
 _HandleEventGarrisonBuildingActivated = <function> defined @Grail\Grail.lua:6754
 bitMaskClassAll = 268443644
 _HandleEventLootClosed = <function> defined @Grail\Grail.lua:6782
 bitMaskQuestLegendary = 4096
 _RemoveDelayedNotification = <function> defined @Grail\Grail.lua:5187
 reputationFriends = <table> {
 }
 NPC_TYPE_BY = "BY"
 NPC_TYPE_DROP = "DROP"
 _PostDelayedNotification = <function> defined @Grail\Grail.lua:8463
 _MarkQuestType = <function> defined @Grail\Grail.lua:5556
 receivedCalendarUpdateEventList = false
 bitMaskClassDeathKnight = 4
 QuestNPCPrerequisiteTurnins = <function> defined @Grail\Grail.lua:9525
 _ProcessServerBackup = <function> defined @Grail\Grail.lua:8885
 bitMaskQuestVariableLevel = 4278190080
 MeetsRequirementGroup = <function> defined @Grail\Grail.lua:8045
_EvaluateCodeAsPrerequisite = <function> defined @Grail\Grail.lua:6071
 bitMaskInLog = 16
 bitMaskQuestWeekly = 4
 bitMaskHolidayNoble = 256
 MeetsRequirementProfession = <function> defined @Grail\Grail.lua:8130
 DoesNPCExist = <function> defined @Grail\Grail.lua:6036
 npcNames = <table> {
 }
 _AllEvaluateTrueS = <function> defined @Grail\Grail.lua:3756
 bitMaskQuestFailureWithAncestor = 67043200
 verifyTable = <table> {
 }
 _NPCToUse = <function> defined @Grail\Grail.lua:8316
 garrisonBuildingLevelMapping = <table> {
 }
 bitMaskClassHunter = 16
 _LoadContinentData = <function> defined @Grail\Grail.lua:3218
 bitMaskQuestRaid = 128
 _LocationStructure = <function> defined @Grail\Grail.lua:7612
 _HandleEventAchievementEarned = <function> defined @Grail\Grail.lua:6749
 checksReputationRewardsOnAcceptance = true
 classToMapAreaMapping = <table> {
 }
 verifyTableCount = 0
 playerGenderBitMask = 8192
 _ReputationExceeds = <function> defined @Grail\Grail.lua:9982
 bitMaskRaceUnused9 = 4096
 zonesForLootingTreasure = <table> {
 }
 bitMaskQuestMonthly = 8
 mapAreaBaseClass = 200000
 exists73 = true
 LearnObjectName = <function> defined @Grail\Grail.lua:7538
 _ContainsAliasNPC = <function> defined @Grail\Grail.lua:5777
 classToBitMapping = <table> {
 }
 FriendshipReputationNameAndLevelName = <function> defined @Grail\Grail.lua:10081
 QuestBreadcrumbs = <function> defined @Grail\Grail.lua:9190
 NPCName = <function> defined @Grail\Grail.lua:8268
 experimental = false
 bitMaskRaceNightborne = 2
 mapAreaBaseReputation = 400000
UnregisterObserverQuestStatus = <function> defined @Grail\Grail.lua:10628
 tooltipNPC = com_mithrandir_grailTooltipNPC {
 }
 _FactionsFromQuestGivers = <function> defined @Grail\Grail.lua:7947
 QuestOnAcceptCompletes = <function> defined @Grail\Grail.lua:9537
 bitMaskAncestorLevelTooHigh = 33554432
 bitMaskRaceTroll = 16777216
 bitMaskCanGetUnused2 = 65536
 celebratingHolidayCache = <table> {
 }
 bitMaskQuestMinLevel = 65280
 bitMaskLevelTooHigh = 32768
 IsGroup = <function> defined @Grail\Grail.lua:7101
 bitMaskCanGetUnused8 = 4194304
 bitMaskCanGetUnused15 = 1073741824
 MeetsRequirementGroupPossibleToComplete = <function> defined @Grail\Grail.lua:8073
 questReputations = <table> {
 }
 _AddThreatQuest

**Comment by smaitch** [comment] 2020-03-16 21:04
I am closing this as a duplicate of https://github.com/smaitch/Grail/issues/140 as I believe the general processing is taking too long for some players.

**Closed by smaitch** 2020-03-16 21:04 UTC
