### ISSUE TITLE
Grail\Grail-111.lua:7142: Usage: GetBuildings(garrisonType)

### ISSUE THREAD

**Issue by MarkusSB** [smaitch/Grail#237] opened 2020-10-18 18:38 UTC
3x Grail\Grail-111.lua:7142: Usage: GetBuildings(garrisonType)
[string "=[C]"]: in function `GetBuildings'
[string "@Grail\Grail-111.lua"]:7142: in function `HasGarrisonBuilding'
[string "@Grail\Grail-111.lua"]:7172: in function `HasGarrisonBuildingInPlot'
[string "@Grail\Grail-111.lua"]:6432: in function `f'
[string "@Grail\Grail-111.lua"]:3694: in function `_AllEvaluateTrueF'
[string "@Grail\Grail-111.lua"]:3797: in function `_AnyEvaluateTrueF'
[string "@Grail\Grail-111.lua"]:9773: in function <Grail\Grail.lua:9740>
[string "=(tail call)"]: ?
[string "@Grail\Grail-111.lua"]:10040: in function `QuestsInMap'
[string "@Wholly\Wholly-080.lua"]:1432: in function `_ClassifyQuestsInMap'
[string "@Wholly\Wholly-080.lua"]:3274: in function `_RecordTooltipNPCs'
[string "@Wholly\Wholly-080.lua"]:669: in function `?'
[string "@Wholly\Wholly-080.lua"]:2532: in function `_OnEvent'
[string "@Wholly\Wholly-080.lua"]:4433: in function <Wholly\Wholly.lua:4433>

Locals:
(*temporary) = nil
(*temporary) = <table> {
}

**Comment by smaitch** [comment] 2020-10-18 18:48
This should be fixed in the current version of Grail that is available on GitHub (and therefore, when the next version of Grail is released).

**Comment by smaitch** [comment] 2020-10-18 18:49
Duplicate of https://github.com/smaitch/Grail/issues/232

**Closed** 2020-10-18 18:49 UTC
